version: '3.8'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres:14
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${POSTGRESQL_DB}
        POSTGRES_USER: ${POSTGRESQL_USER}
        POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
  keycloak:
      image: quay.io/keycloak/keycloak:nightly
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: ${POSTGRESQL_DB}
        DB_USER: ${POSTGRESQL_USER}
        DB_SCHEMA: public
        DB_PASSWORD: ${POSTGRESQL_PASS}
        KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      ports:
        - 9000:8080
      command: start-dev
      depends_on:
          - postgres